### ISSUE TITLE
Repository does not include license information

### ISSUE THREAD

**Issue by dR3b** [mrclksr/NomadBSD#4]
Please add a LICENSE file with appropriate contents to the root of this repository.

* [ISC](https://en.wikipedia.org/wiki/ISC_license)
* [BSD](https://en.wikipedia.org/wiki/BSD_licenses)
* [MIT](https://en.wikipedia.org/wiki/MIT_License)
* [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License)

Thanks

**Comment by mrclksr** [comment]
Done. :)
