### ISSUE TITLE
wifi don't start 

### ISSUE THREAD

**Issue by trassiorf** [mrclksr/NomadBSD#8]
I must configure manually this file to start wifi :+1: 
/etc/rc.conf
wlans_rtwn0="wlan0"
ifconfig_wlan0="WPA DHCP"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/etc/wpa_supplicant.conf
network={
        ssid="**********"
        proto=WPA2
        key_mgmt=WPA-PSK
        pairwise=CCMP
        psk="************"
        priority=5
}
Without this manually setup above I can't start wifi with network ==>> wifi manager

**Comment by mrclksr** [comment]
Thank you.

There is no record for `rtwn(4)` in the DSBDriverd's `drivers.db`, yet. This is why the automatic setup failed. The change will be available in RC2.

**Comment by Ygarr** [comment]
Also this regarding to Dual Band Wireless-AC 3168 NGW aka iwm3168fw

**Comment by trassiorf** [comment]
Can you add record for 'run' ?
How can I add myself this record in drivers.db ?
Thank

**Comment by trassiorf** [comment]
Oh! run seems to be compiled into the base
Why run usb key don't start automatically ?

**Comment by mrclksr** [comment]
@Ygarr 
> Also this regarding to Dual Band Wireless-AC 3168 NGW aka iwm3168fw

Alright. The record for if_iwm has been updated.

@trassiorf 
> Can you add record for 'run' ?

I will update the `if_run` record.

> How can I add myself this record in drivers.db ?

Open `/usr/local/share/dsbdriverd/drivers.db` with a text editor. You'll find a description of the file format in the first few lines. Then look for `if_run`, and then for the vendor ID. Add the device ID of your wifi adapter to the list of device IDs under the matching vendor. But I'd recommend to add
```
if_run_load="YES"
runfw_load="YES"

```
to `/boot/loader.conf`

> Oh! run seems to be compiled into the base
> Why run usb key don't start automatically ?

`if_run` is not built into the kernel. But it's available as kernel module.

**Comment by mrclksr** [comment]
The record for `if_run` has been updated. You can download and copy https://github.com/mrclksr/DSBDriverd/blob/master/drivers.db to `/usr/local/share/dsbdriverd/drivers.db`. After restarting `dsbdriverd` with `service dsbdriverd restart` it should detect your device.

**Comment by time-killer-games** [comment]
I think the info in the OP of this issue should be linked to in the readme if anyone has trouble setting up their wifi, I had to do the same thing to get it working, but I had to replace `wlans_rtwn0` with `wlans_rum0` to match my wireless adapter.

**Comment by bsdlme** [comment]
> I think the info in the OP of this issue should be linked to in the readme if anyone has trouble setting up their wifi, I had to do the same thing to get it working, but I had to replace `wlans_rtwn0` with `wlans_rum0` to match my wireless adapter.

Generally it's a useful information. But we should have fixed the issue in the meantime.
